import { Telegraf, Markup } from 'telegraf';
import { TelegramUserStore } from './userStore.js';
import { ConversationStore } from './conversationStore.js';
import { normalizePhone, validPrefix, isAdmin, downloadTelegramPhoto, publicStatus } from './telegramUtils.js';

const mainKeyboard = () => Markup.inlineKeyboard([[Markup.button.callback('🤖 Créer un bot', 'create')], [Markup.button.callback('📦 Mes bots', 'bots')], [Markup.button.callback('⚙️ Paramètres', 'settings'), Markup.button.callback('ℹ️ Aide', 'help')]]);
const cancelKeyboard = () => Markup.inlineKeyboard([[Markup.button.callback('❌ Annuler', 'cancel')]]);
const idOf = ctx => ctx.from?.id;
const text = ctx => String(ctx.message?.text ?? '').trim();
const safe = async (ctx, operation, logger) => { try { return await operation(); } catch (error) { logger.error({ error: error.message, telegramUserId: idOf(ctx) }, 'Telegram operation failed'); await ctx.reply('❌ Une erreur est survenue.'); return null; } };

export function createTelegramBot({ forge, logger = forge.logger, userStore = new TelegramUserStore(), conversations = new ConversationStore() } = {}) {
  const token = process.env.TELEGRAM_BOT_TOKEN;
  if (!token) { logger.warn('TELEGRAM_BOT_TOKEN is not configured; Telegram manager disabled'); return { launch: async () => {}, stop: () => {} }; }
  const bot = new Telegraf(token);
  const start = async ctx => safe(ctx, async () => { await userStore.createUser(idOf(ctx)); await ctx.reply('╭━━━〔 NEXUS FORGE 〕━━━╮\n│\n│ 🤖 Bienvenue sur Nexus Forge\n│\n│ Crée et gère tes bots WhatsApp\n│ directement depuis Telegram.\n│\n╰━━━━━━━━━━━━━━━━━━━━━━╯', mainKeyboard()); }, logger);
  const begin = async ctx => safe(ctx, async () => { await ctx.answerCbQuery?.(); const state = await conversations.start(idOf(ctx)); logger.info({ telegramUserId: idOf(ctx), creationId: state.creationId }, 'Telegram creation started'); await ctx.reply('Quel nom veux-tu donner à ton bot WhatsApp ?', cancelKeyboard()); }, logger);
  const prompt = async (ctx, question, step) => { conversations.update(idOf(ctx), { step }); await ctx.reply(question, cancelKeyboard()); };
  const next = async ctx => safe(ctx, async () => { const id = idOf(ctx); const state = conversations.get(id); if (!state) return ctx.reply('Cette création a expiré. Recommence avec le bouton Créer un bot.'); const value = text(ctx); if (state.step === 'botName') { if (!value || value.length > 80) throw new Error('Invalid name'); state.data.botName = value; return prompt(ctx, 'Envoie la photo du menu, ou utilise /skip pour la photo par défaut.', 'photo'); } if (state.step === 'ownerName') { if (!value || value.length > 80) throw new Error('Invalid owner'); state.data.ownerName = value; return prompt(ctx, 'Quel est le numéro WhatsApp de l’owner ?', 'ownerNumber'); } if (state.step === 'ownerNumber') { state.data.ownerNumber = normalizePhone(value); return prompt(ctx, 'Quel numéro WhatsApp veux-tu utiliser pour ton bot ?', 'botPhoneNumber'); } if (state.step === 'botPhoneNumber') { state.data.botPhoneNumber = normalizePhone(value); return prompt(ctx, 'Quel nom afficher comme développeur ? (ou « même »)', 'developerName'); } if (state.step === 'developerName') { state.data.developerName = value.toLowerCase() === 'même' ? state.data.ownerName : value; if (!state.data.developerName) throw new Error('Invalid developer'); return prompt(ctx, 'Quel préfixe veux-tu utiliser ? (ex: !)', 'prefix'); } if (state.step === 'prefix') { if (!validPrefix(value)) throw new Error('Invalid prefix'); state.data.prefix = value; state.data.mode = 'public'; return summary(ctx, state); } }, logger);
  const photo = async ctx => safe(ctx, async () => { const state = conversations.get(idOf(ctx)); if (!state || state.step !== 'photo') return; state.data.photoPath = await downloadTelegramPhoto(ctx, idOf(ctx), conversations); return prompt(ctx, 'Quel nom doit être utilisé pour l’owner de ton bot ?', 'ownerName'); }, logger);
  const skip = async ctx => safe(ctx, async () => { const state = conversations.get(idOf(ctx)); if (!state) return; state.data.photoPath = null; return prompt(ctx, 'Quel nom doit être utilisé pour l’owner de ton bot ?', 'ownerName'); }, logger);
  const summary = async (ctx, state = conversations.get(idOf(ctx))) => ctx.reply(`╭━━〔 CONFIGURATION 〕━━╮\n\n🤖 Nom : ${state.data.botName}\n👤 Owner : ${state.data.ownerName}\n📱 Numéro Owner : +${state.data.ownerNumber}\n📱 Numéro Bot : +${state.data.botPhoneNumber}\n👨‍💻 Développeur : ${state.data.developerName}\n🔧 Préfixe : ${state.data.prefix}\n🌍 Mode : Public\n🖼️ Photo : ${state.data.photoPath ? 'Personnalisée' : 'Par défaut'}\n\n╰━━━━━━━━━━━━━━━━━━━━━━╯\nTout est correct ?`, Markup.inlineKeyboard([[Markup.button.callback('✅ Créer le bot', 'confirm'), Markup.button.callback('✏️ Modifier', 'edit')], [Markup.button.callback('❌ Annuler', 'cancel')]]));
  const confirm = async ctx => safe(ctx, async () => { const state = conversations.get(idOf(ctx)); if (!state) throw new Error('Creation expired'); const created = await forge.createInstance({ ...state.data, menuImage: undefined }); if (state.data.photoPath) await forge.setMenuImage(created.instanceId, state.data.photoPath); await userStore.addInstanceToUser(idOf(ctx), created.instanceId); logger.info({ telegramUserId: idOf(ctx), instanceId: created.instanceId }, 'Telegram instance created'); await conversations.cancel(idOf(ctx)); await ctx.reply(`✅ Ton bot a été créé.\n\n🤖 Nom : ${state.data.botName}\n🆔 ID : ${created.instanceId}\n📱 Numéro : +${state.data.botPhoneNumber}\n📊 Statut : 🟡 Créé`, Markup.inlineKeyboard([[Markup.button.callback('📱 Connecter WhatsApp', `start:${created.instanceId}`)], [Markup.button.callback('⚙️ Gérer le bot', `manage:${created.instanceId}`)], [Markup.button.callback('📦 Mes bots', 'bots')]])); }, logger);
  const cancel = async ctx => safe(ctx, async () => { await conversations.cancel(idOf(ctx)); await ctx.reply('Création annulée.', mainKeyboard()); }, logger);
  const bots = async ctx => safe(ctx, async () => { const ids = await userStore.getUserInstances(idOf(ctx)); if (!ids.length) return ctx.reply('Tu n’as pas encore de bot.', mainKeyboard()); const lines = []; for (const id of ids) { const config = await forge.getInstance(id); lines.push(`🤖 ${config.botName}\n${publicStatus(forge.getInstanceStatus(id))}`); } await ctx.reply(`╭━━〔 MES BOTS 〕━━╮\n\n${lines.join('\n\n')}\n\n╰━━━━━━━━━━━━━━━━╯`, Markup.inlineKeyboard(ids.map(id => [Markup.button.callback('⚙️ Gérer', `manage:${id}`)]))); }, logger);
  const owned = async (ctx, id) => { if (!id || !(await userStore.ownsInstance(idOf(ctx), id))) throw new Error('Unauthorized instance access'); return id; };
  const manage = async ctx => safe(ctx, async () => { const id = await owned(ctx, ctx.match[1]); const config = await forge.getInstance(id); await ctx.reply(`╭━━〔 ${config.botName} 〕━━╮\n\n🆔 ID : ${id}\n📊 Statut : ${publicStatus(forge.getInstanceStatus(id))}\n\n╰━━━━━━━━━━━━━━━━━━━━╯`, Markup.inlineKeyboard([[Markup.button.callback('▶️ Démarrer', `start:${id}`), Markup.button.callback('⏹️ Arrêter', `stop:${id}`)], [Markup.button.callback('🔄 Redémarrer', `restart:${id}`)], [Markup.button.callback('📊 Statut', `status:${id}`), Markup.button.callback('🗑️ Supprimer', `delete:${id}`)], [Markup.button.callback('⬅️ Retour', 'bots')]])); }, logger);
  const action = async ctx => safe(ctx, async () => { const id = await owned(ctx, ctx.match[1]); const actionName = ctx.match[0].split(':')[0]; if (actionName === 'start') await forge.startInstance(id); if (actionName === 'stop') await forge.stopInstance(id); if (actionName === 'restart') await forge.restartInstance(id); if (actionName === 'delete') { await forge.deleteInstance(id); await userStore.removeInstanceFromUser(idOf(ctx), id); } await ctx.answerCbQuery('Action effectuée'); await manage({ ...ctx, match: [`manage:${id}`, id] }); }, logger);
  bot.start(start); bot.command('cancel', cancel); bot.command('skip', skip); bot.action('create', begin); bot.action('bots', bots); bot.action('help', ctx => ctx.reply('Nexus Forge permet de créer et gérer tes bots WhatsApp.', mainKeyboard())); bot.action('settings', ctx => ctx.reply(isAdmin(idOf(ctx)) ? 'Paramètres administrateur disponibles prochainement.' : 'Aucun paramètre disponible.')); bot.action('cancel', cancel); bot.action('confirm', confirm); bot.action('edit', ctx => ctx.reply('Utilise /cancel puis relance la création pour modifier les champs.')); bot.action(/^manage:(.+)$/, manage); bot.action(/^(start|stop|restart|delete):(.+)$/, action); bot.action(/^status:(.+)$/, async ctx => safe(ctx, async () => { const id = await owned(ctx, ctx.match[1]); await ctx.answerCbQuery(publicStatus(forge.getInstanceStatus(id))); }, logger)); bot.on('photo', photo); bot.on('text', next); bot.catch((error, ctx) => logger.error({ error: error.message, telegramUserId: idOf(ctx) }, 'Unhandled Telegram error')); return bot;
}
